server:
    port: 8080
    context-path:

# 配置log
logging:
    config: classpath:log4j2.yml

cron:
  pattern: 0/6 * * * * ?
  enable: disable

# spring配置
spring:
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    #配置jpa,自动映射类到表
    jpa:
        database: MYSQL
        show-sql: true
        hibernate:
            ddlAuto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    output:
        ansi: enabled